version: "3"

services:
  python:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/home/python
    env_file: .env
    container_name: exercise.python.local
    links:
      - db
  db:
    image: mongo:3.0.2
    container_name: exercise_pythons_db

networks:
  default:
    external:
      name: nginx-proxy
